


CREATE TABLE REGION
(
ID_REGION VARCHAR(5)
);

CREATE TABLE CIUDAD
(
ID_CIUDAD VARCHAR(5),
ID_REGION VARCHAR(5)
);

CREATE TABLE ENTRENADOR
(
ID_ENTRENADOR VARCHAR(5),
NOMBRE VARCHAR(10),
NUM_MEDALLAS INT(1),
NUM_POKEMONS INT(3),
ID_CIUDAD VARCHAR(5)
);

CREATE TABLE POKEMON
(
COD_POKEMON VARCHAR(5),
NOMBRE VARCHAR(10),
NIVEL INT(3)
);

CREATE TABLE POKEMON_REGION
(
COD_POKEMON VARCHAR(5),
ID_REGION VARCHAR(5)
);

CREATE TABLE TIPO
(
NOMBRE VARCHAR(10)
);

CREATE TABLE NO_LEGENDARIO
(
COD_POKEMON VARCHAR(5),
NOMBRE VARCHAR(10),
NIVEL INT(3)
);

CREATE TABLE RUTA_POKEMON
(
COD_POKEMON VARCHAR(5),
RUTA VARCHAR(12)
);

CREATE TABLE LEGENDARIO
(
COD_POKEMON VARCHAR(5),
NOMBRE VARCHAR(10),
NIVEL INT(3),
LUGAR VARCHAR(30)
);

CREATE TABLE GIMNASIO
(
NOMBRE VARCHAR(10),
TIPO_PREDOMINANTE VARCHAR(15),
LIDER VARCHAR(8),
ID_CIUDAD VARCHAR(5)
);

CREATE TABLE CENTRO_POKEMON
(
NOMBRE VARCHAR(10),
NUM_ENFERMEROS_DISPONIBLES INT(2),
ID_CIUDAD VARCHAR(5)
);

CREATE TABLE CAPTURA
(
COD_POKEMON VARCHAR(5),
ID_ENTRENADOR VARCHAR(5)
);

CREATE TABLE POSEE
(
COD_POKEMON VARCHAR(5),
NOMBRE VARCHAR(10)
);


ALTER TABLE REGION ADD CONSTRAINT PK_REGION PRIMARY KEY(ID_REGION);

ALTER TABLE CIUDAD ADD CONSTRAINT PK_CIUDAD PRIMARY KEY(ID_CIUDAD);
ALTER TABLE CIUDAD ADD CONSTRAINT FK1_CIUDAD FOREIGN KEY(ID_REGION) REFERENCES REGION(ID_REGION);

ALTER TABLE ENTRENADOR ADD CONSTRAINT PK_ENTRENADOR PRIMARY KEY(ID_ENTRENADOR);
ALTER TABLE ENTRENADOR ADD CONSTRAINT FK1_ENTRENADOR FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD);

ALTER TABLE POKEMON ADD CONSTRAINT PK_POKEMON PRIMARY KEY(COD_POKEMON);

ALTER TABLE POKEMON_REGION ADD CONSTRAINT PK_POKEMON_REGION PRIMARY KEY(COD_POKEMON);
ALTER TABLE POKEMON_REGION ADD CONSTRAINT FK1_POKEMON_REGION FOREIGN KEY(ID_REGION) REFERENCES REGION(ID_REGION);

ALTER TABLE TIPO ADD CONSTRAINT PK_TIPO PRIMARY KEY(NOMBRE);

ALTER TABLE NO_LEGENDARIO ADD CONSTRAINT FK1_NO_LEGENDARIO FOREIGN KEY (COD_POKEMON) REFERENCES POKEMON(COD_POKEMON);
ALTER TABLE NO_LEGENDARIO ADD CONSTRAINT PK_NO_LEGENDARIO PRIMARY KEY (COD_POKEMON);

ALTER TABLE RUTA_POKEMON ADD CONSTRAINT FK1_RUTA_POKEMON FOREIGN KEY(COD_POKEMON) REFERENCES POKEMON(COD_POKEMON);
ALTER TABLE RUTA_POKEMON ADD CONSTRAINT PK_RUTA_POKEMON PRIMARY KEY(COD_POKEMON);

ALTER TABLE LEGENDARIO ADD CONSTRAINT FK1_LEGENDARIO FOREIGN KEY(COD_POKEMON) REFERENCES POKEMON(COD_POKEMON);
ALTER TABLE LEGENDARIO ADD CONSTRAINT PK_LEGENDARIO PRIMARY KEY(COD_POKEMON);

ALTER TABLE GIMNASIO ADD CONSTRAINT PK_GIMNASIO PRIMARY KEY(NOMBRE);
ALTER TABLE GIMNASIO ADD CONSTRAINT FK1_GIMNASIO FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD);

ALTER TABLE CENTRO_POKEMON ADD CONSTRAINT PK_CENTRO_POKEMON PRIMARY KEY(NOMBRE);
ALTER TABLE CENTRO_POKEMON ADD CONSTRAINT FK1_CENTRO_POKEMON FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD);

ALTER TABLE CAPTURA ADD CONSTRAINT FK1_CAPTURA FOREIGN KEY(COD_POKEMON) REFERENCES POKEMON(COD_POKEMON);
ALTER TABLE CAPTURA ADD CONSTRAINT PK_CAPTURA PRIMARY KEY(COD_POKEMON);
ALTER TABLE CAPTURA ADD CONSTRAINT FK2_CAPTURA FOREIGN KEY(ID_ENTRENADOR) REFERENCES ENTRENADOR(ID_ENTRENADOR);

ALTER TABLE POSEE ADD CONSTRAINT FK1_POSEE FOREIGN KEY(COD_POKEMON) REFERENCES POKEMON (COD_POKEMON);
ALTER TABLE POSEE ADD CONSTRAINT FK2_POSEE FOREIGN KEY(NOMBRE) REFERENCES TIPO(NOMBRE);
ALTER TABLE POSEE ADD CONSTRAINT PK_POSEE PRIMARY KEY (COD_POKEMON, NOMBRE);


INSERT INTO REGION VALUES ('00001');
INSERT INTO CIUDAD VALUES ('00001','00001');
INSERT INTO ENTRENADOR VALUES('00001','ALEJANDRO','5','6','00001');
INSERT INTO POKEMON VALUES ('00001','CHARMANDER','5');
INSERT INTO POKEMON_REGION VALUES ('00001','00001');
INSERT INTO TIPO VALUES('FUEGO');
INSERT INTO NO_LEGENDARIO VALUES('00001','CHARMANDER','5');
INSERT INTO RUTA_POKEMON VALUES('00001','VOLCAN');
INSERT INTO LEGENDARIO VALUES('00001','MEWTWO','50','CUEVA CELESTE');
INSERT INTO GIMNASIO VALUES('GIMNASIO','ROCA','BROCK','00001');
INSERT INTO CENTRO_POKEMON VALUES ('MEDICO','15','00001');
INSERT INTO CAPTURA VALUES ('00001','00001');
INSERT INTO POSEE VALUES('00001','FUEGO');





